### ISSUE TITLE
Action on Cancel button

### ISSUE THREAD

**Issue by Kinomad** [camilo1498/stories_editor#1]
Hi! 
Congratulations for your a great job! I tried on iOS, it's work pretty well and really pleasant to use it :) Some feature are even more confortable than insta :))

On iOS, you have a close button on the top left, but nothing happen when I click on it. I would like to be back to my previous screen. For now, I use my a Widget with "middleBottomWidget" to have a cancel button but it will be nicer to use your original button :) Or how to manage somes actions on it like you can do with the onDone ? 

I'm really glad to use this new package and excited to see the next evolution :)
Thank you for your work!

**Comment by camilo1498** [comment]
Hi kinomad!, thanks for giving feedback on this project, I'm glad to have your help, the problem with that button is that it doesn't have any onDone function since I forgot to implement it 😅, I'm working on an update to improve performance, remove provider and fix some issues like that of that button, in the next few days or weeks I hope to be able to give an update (i am a junior dev, be patient with me 😅)

**Comment by Kinomad** [comment]
No worries, I'm also newbie in Flutter and glad if I can help for testing :)

That's really good if you can remove the provider, because for the moment, I didn't find a way to add it inside the list of my other Providers. For example : `providers: [ StoriesEditorProvider().providers ]` doesn't work and say : "_The element type 'List<SingleChildWidget>' can't be assigned to the list type 'SingleChildWidget'_". 

Thanks in advance for the cancel button and next improvement!
